name: syncfusion_flutter_maps
description: A Flutter Maps library for creating beautiful, interactive, and customizable maps from shape files or WMTS services to visualize the geographical area.
version: 24.2.9
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_maps

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_core: ^24.2.6

  http: ^1.0.0
  vector_math: ">=2.1.0 <=3.0.0"
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
